### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by jacob755** [Lemonsavery/openUrlsWhenLoaded#30]
hello 
nice light extension thank you i have feature request
ability to open only defined number of url to open and clear them from box
say i entered 50 link i want ext only open first 10 link then clear them from box
thank you

**Comment by Lemonsavery** [comment]
@jacob755 When a limited number to open for this feature is defined, when should links be cleared from the box? Should:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- each link be cleared after it is fully loaded? *(clear links as tool is running)*
or
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- all links opened with this feature are cleared once all have been loaded? *(clear links when finished)*

**Comment by jacob755** [comment]
> 


thanks for replay

 before opening link,just user define how many link open then ext open one by one till user defined number reached and ext should stop opening link and then clear opened link(clear links when finished) and keep the rest of link in box.
here we have 5 url
https://www.google.com
https://www.google.com/search?q=hat
https://www.google.com/search?q=shoe
https://www.google.com/search?q=shirt
https://www.google.com/search?q=pants

i set open first 3 url
Sequential Mass URL Opener open 3 first url one by one (not all in once,however this can be option too)
then 3 first url cleared from box urls so i know which url remain which opened

**Comment by Lemonsavery** [comment]
I've added this feature in [Release 2.3](https://github.com/Lemonsavery/openUrlsWhenLoaded/releases/tag/2.3). This release has been submitted and will be published, once it's approved by the Chrome Web Store.

**Comment by Lemonsavery** [comment]
@jacob755 Thanks for the suggestion!

**Comment by Lemonsavery** [comment]
@jacob755 If you have a sec, [leaving a review for the extension](https://chrome.google.com/webstore/detail/sequential-mass-url-opene/lgffephbjkjmkdipchghjadbeppgojhk) would be cool. If not, that's fine too.

**Comment by jacob755** [comment]
> @jacob755 If you have a sec, [leaving a review for the extension](https://chrome.google.com/webstore/detail/sequential-mass-url-opene/lgffephbjkjmkdipchghjadbeppgojhk) would be cool. If not, that's fine too.

done thanks for fast update downloaded already from here and using it
best regards
